### ISSUE TITLE
Error when installing script

### ISSUE THREAD

**Issue by MartinSStewart** [ianmackenzie/elm-script#14]
I followed the instructions in the readme to install elm-script but I'm getting this error
```
% deno install -A -n elm-script ~/elm-script/runner/main.js
Download https://deno.land/std/path/mod.ts
Warning Implicitly using master branch https://deno.land/std/path/mod.ts
Download https://deno.land/std/path/_constants.ts
Download https://deno.land/std/path/win32.ts
Download https://deno.land/std/path/posix.ts
Download https://deno.land/std/path/common.ts
Download https://deno.land/std/path/separator.ts
Download https://deno.land/std/path/_interface.ts
Download https://deno.land/std/path/glob.ts
Warning Implicitly using master branch https://deno.land/std/path/glob.ts
Download https://deno.land/std/path/_globrex.ts
Download https://deno.land/std/testing/asserts.ts
Warning Implicitly using master branch https://deno.land/std/path/_interface.ts
Warning Implicitly using master branch https://deno.land/std/path/_constants.ts
Warning Implicitly using master branch https://deno.land/std/path/win32.ts
Download https://deno.land/std/path/_util.ts
Warning Implicitly using master branch https://deno.land/std/path/common.ts
Warning Implicitly using master branch https://deno.land/std/path/separator.ts
Warning Implicitly using master branch https://deno.land/std/path/posix.ts
Warning Implicitly using master branch https://deno.land/std/path/_globrex.ts
Warning Implicitly using master branch https://deno.land/std/testing/asserts.ts
Download https://deno.land/std/fmt/colors.ts
Download https://deno.land/std/testing/diff.ts
Warning Implicitly using master branch https://deno.land/std/path/_util.ts
Warning Implicitly using master branch https://deno.land/std/fmt/colors.ts
Warning Implicitly using master branch https://deno.land/std/testing/diff.ts
Compile file:///Users/martinstewart/elm-script/runner/main.js
error: Uncaught AssertionError: Unexpected skip of the emit.
    at Object.assert ($deno$/util.ts:33:11)
    at compile ($deno$/compiler.ts:1170:7)
    at tsCompilerOnMessage ($deno$/compiler.ts:1338:22)
    at workerMessageRecvCallback ($deno$/runtime_worker.ts:72:33)
    at file:///Users/martinstewart/elm-script/__anonymous__:1:1
```

I'm running on Mac OS
```
% deno --version
deno 1.0.4
v8 8.4.300
typescript 3.9.2
```

**Comment by ianmackenzie** [comment]
Hmm tricky, haven't seen that one before...I wonder if those warnings are the key, though, it's implicitly getting the current development version of various standard library modules instead of an official release. Can you try changing line 6 of `main.js` to

```
import * as path from "https://deno.land/std@1.0.4/path/mod.ts";
```
or perhaps even an older version like

```
import * as path from "https://deno.land/std@1.0.0/path/mod.ts";
```

and see if that works?

**Comment by ianmackenzie** [comment]
Oops actually it looks like the standard library has a different version number, so maybe try `std@0.55.0` (latest stable release) or `std@0.50.0` (which looks like it should be the version that corresponded to Deno 1.0) or something in that range...

**Comment by MartinSStewart** [comment]
I'm getting similar looking output when I use either 0.50.0 or 0.55.0
```
% deno install -A -n elm-script ~/elm-script/runner/main.js
Download https://deno.land/std@0.55.0/path/mod.ts
Download https://deno.land/std@0.55.0/path/_constants.ts
Download https://deno.land/std@0.55.0/path/win32.ts
Download https://deno.land/std@0.55.0/path/posix.ts
Download https://deno.land/std@0.55.0/path/common.ts
Download https://deno.land/std@0.55.0/path/separator.ts
Download https://deno.land/std@0.55.0/path/_interface.ts
Download https://deno.land/std@0.55.0/path/glob.ts
Download https://deno.land/std@0.55.0/path/_util.ts
Download https://deno.land/std@0.55.0/testing/asserts.ts
Download https://deno.land/std@0.55.0/fmt/colors.ts
Download https://deno.land/std@0.55.0/testing/diff.ts
Download https://deno.land/std@0.55.0/path/_globrex.ts
Compile file:///Users/martinstewart/elm-script/runner/main.js
error: Uncaught AssertionError: Unexpected skip of the emit.
    at Object.assert ($deno$/util.ts:33:11)
    at compile ($deno$/compiler.ts:1170:7)
    at tsCompilerOnMessage ($deno$/compiler.ts:1338:22)
    at workerMessageRecvCallback ($deno$/runtime_worker.ts:72:33)
    at file:///Users/martinstewart/elm-script/__anonymous__:1:1
```

**Comment by MartinSStewart** [comment]
I tried running `deno install -A -n elm-script ~/elm-script/runner/main.js` on a Windows 10 computer  (no change to the line 6 import) and got the same error as I did on my Mac computer.

**Comment by ianmackenzie** [comment]
Ah interesting! Yeah, just tested locally and I do get the same error if I update to 1.0.4 (I was on 1.0.0). 'Upgrading' to 1.0.3 seemed to make the problem go away for me: `deno upgrade --version 1.0.3`.

Not sure how to best figure out whether this is a Deno issue or an `elm-script` issue...kind of tempted to wait for 1.0.5 and see what happens 🙂

**Comment by MartinSStewart** [comment]
Thanks, that gets me farther along. Now I'm getting `error: The system cannot find the path specified. (os error 3)` both on Windows and Mac. I'm pretty sure I'm giving it the correct path though.

**Comment by ianmackenzie** [comment]
Huh weird - that's during the install step? I wonder if the problem is not that the path to `main.js` is wrong, but that Deno is trying to put the wrapper executable script in a particular directory and that directory doesn't exist. The [docs](https://deno.land/manual/tools/script_installer) mention that the wrapper script is installed to "the installation root's `bin` directory" - maybe figure out where the Deno installation root is on your machine and make sure there's a `bin` directory? I don't remember having to do that myself, though...

BTW the original error does look like an internal assert in the Deno compiler source: https://github.com/denoland/deno/blob/9c59a4b18c0aac3699d210c1f05f152651ddca28/cli/js/compiler.ts#L1170. If it's not fixed in 1.0.5 then I can look at trying to submit a nice issue.

**Comment by MartinSStewart** [comment]
Here's the exact output I'm getting now (on my Mac with the 0.55.0 import)
```
 % deno install -A -n elm-script ~/elm-script/runner/main.js
Download https://deno.land/std@0.50.0/path/mod.ts
Download https://deno.land/std@0.50.0/path/win32.ts
Download https://deno.land/std@0.50.0/path/posix.ts
Download https://deno.land/std@0.50.0/path/common.ts
Download https://deno.land/std@0.50.0/path/separator.ts
Download https://deno.land/std@0.50.0/path/interface.ts
Download https://deno.land/std@0.50.0/path/glob.ts
Download https://deno.land/std@0.50.0/path/_globrex.ts
Download https://deno.land/std@0.50.0/testing/asserts.ts
Download https://deno.land/std@0.50.0/path/_constants.ts
Download https://deno.land/std@0.50.0/path/_util.ts
Download https://deno.land/std@0.50.0/fmt/colors.ts
Download https://deno.land/std@0.50.0/testing/diff.ts
error: No such file or directory (os error 2)
```

I'll look into if I've messed up something with Deno's installation

**Comment by ianmackenzie** [comment]
One thing you might be able to try is skip the `deno install` step; for example, from the root of an `elm-script` checkout, instead of

```
elm-script run examples/HelloWorld.elm
```

try running

```
deno run -A runner/main.js run examples/HelloWorld.elm
```

instead. That might help narrow down whether the issue is with downloading dependencies (which should happen pretty much the same way in either version) or with installing the wrapper script (which the second version bypasses).

**Comment by MartinSStewart** [comment]
I got it to work now (on Windows at least, I haven't tested Mac) by using Deno 1.0.0 instead. Strange that Deno gets buggier with each patch release 😄

**Comment by ianmackenzie** [comment]
Yeah that's a bit concerning 😬

Thanks for working through all this! Deno and `elm-script` are both pretty young, hopefully this all gets smoother over time...

**Comment by ianmackenzie** [comment]
OK, I'll leave this open for now to remind myself to check if this gets fixed in a future patch release of Deno, but I've also created #15 to switch to importing a specific tagged version of the standard library. That should avoid the warnings you initially encountered and seems like the right approach in general...

**Comment by ianmackenzie** [comment]
Deno version 1.1 seems to have resolved this for me - can you try and see if it works for you?

Deno 1.1 did introduce another issue (or at least change in behavior) where it seems to always 'recompile' local .js files - so if you use the current installation instructions, you'll get an annoying pause every time you run `elm-script` as it 'recompiles' `runner/main.js`. As a workaround, I've uploaded the current version of the runner to https://elm-script.github.io/0.2; you should be able to run

```
deno install -f -A -n elm-script https://elm-script.github.io/0.2
```

to overwrite your current `elm-script` with the version published over HTTP (which I guess Deno generally trusts won't change over time, so doesn't try to re-download/recompile). You can still use the old instructions to 'link' to the local version of `runner/main.js` if you're trying out some local modifications; I'll update the README accordingly.

**Comment by MartinSStewart** [comment]
I believe it resolved it for me too without me realizing it. I installed deno on another computer, installed elm-script, and everything went smoothly. I just checked and that version was 1.1

I haven't tried using elm-script from the url but the recompile time doesn't seem so bad. I might try it later though.
